### ISSUE TITLE
useElementSize returns 0 width/height on initial render

### ISSUE THREAD

**Issue by lancepollard** [juliencrn/usehooks.ts#32]
It is only after resizing the browser window that the size is correct. This means initial render you get size 0 and can't style it in a custom way. How do you work around this?

**Comment by juliencrn** [comment]
Oh, good catch, it's weird. Thanks @lancepollard, I will check it and I'm come back to you.

**Comment by juliencrn** [comment]
I've just tried (using [this example](https://usehooks-typescript.com/react-hook/use-element-size)). Indeed, at the initial render, the width/height has size 0. It's the default value, and it's because until the component is mounted, we can't calculate his size. 
But, when the component is mounted, the `useEffect` in the hook is triggered and give you the element size.
It works as expected. 

![Screenshot 2021-09-19 at 13 51 00](https://user-images.githubusercontent.com/14028029/133926662-db526488-aa1f-4a04-8e13-90a812391cec.png)


I think your problem is coming from utilization of the `ref` given to the hook.

Can you share your code to be able to fix it ?
